export const travOffers = [
  {
    name: 'Dream trip to Salzburg',
    destination:"Salzburg, Austria",
    stDate:'12.11.2020',
    duration:'3 Days',
    img: 'assets/salzburg.jpg',
    imgThum:'assets/salzburg-thumbnail.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:149.99,
  },{
    name: 'A trip to Bratis(lover)',
    destination:"Bratislava, Slovakia",
    stDate:'03.12.2020',
    duration:'4 Days',
    img: 'assets/bratislava.jpg',
    imgThum:'assets/bratislava-thumbnail.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:129.99,
  },{
    name: '2 Days in Venice',
    destination:"Venice, Italy",
    stDate:'29.10.2020',
    duration:'2 Days',
    img: 'assets/venice.jpg',
    imgThum:'assets/venice-thumbnail.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:99.99,
  },{
    name: 'a fun Week in Amsterdam',
    destination:"Amsterdam, Netherlands",
    stDate:'23.11.2020',
    duration:'1 Week',
    img: 'assets/amsterdam.jpg',
    imgThum:'assets/amsterdam-thumbnail.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:499.99,
  },{
    name: 'A fancy weekend in Paris',
    destination:"Paris, France",
    stDate:'06.11.2020',
    duration:'3 Days',
    img: 'assets/paris.jpg',
    imgThum:'assets/paris-thumbnail.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:499.99,
  },{
    name: 'Celebrate New Year’s Eve In London',
    destination:"London, England",
    stDate:'30.12.2020',
    duration:'4 Days',
    img: 'assets/london.jpg',
    imgThum:'assets/london-thumbnail.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    price:649.99,
  },
];
